apiVersion: v1
kind: ServiceAccount
metadata:
  name: auth-service
  namespace: default
  labels:
    app: auth-service
    tier: backend
automountServiceAccountToken: true
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: gateway-service
  namespace: default
  labels:
    app: gateway-service
    tier: backend
automountServiceAccountToken: true
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: user-service
  namespace: default
  labels:
    app: user-service
    tier: backend
automountServiceAccountToken: true
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: notification-service
  namespace: default
  labels:
    app: notification-service
    tier: backend
automountServiceAccountToken: true
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: admin-ui-service
  namespace: default
  labels:
    app: admin-ui
    tier: frontend
automountServiceAccountToken: true
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: orion-service-account
  namespace: default
  labels:
    app: orion-platform
  annotations:
    description: "Service account for ORION platform services with Vault access"
automountServiceAccountToken: true
