# Custom PostgreSQL Exporter Queries for ORION Platform

# Database size metrics
pg_database_size:
  query: "SELECT pg_database.datname, pg_database_size(pg_database.datname) as size_bytes FROM pg_database"
  master: true
  metrics:
    - datname:
        usage: "LABEL"
        description: "Name of the database"
    - size_bytes:
        usage: "GAUGE"
        description: "Size of the database in bytes"

# Table size metrics
pg_table_size:
  query: |
    SELECT
      schemaname,
      tablename,
      pg_total_relation_size(schemaname||'.'||tablename) AS total_bytes,
      pg_relation_size(schemaname||'.'||tablename) AS table_bytes,
      pg_indexes_size(schemaname||'.'||tablename) AS index_bytes
    FROM pg_tables
    WHERE schemaname NOT IN ('pg_catalog', 'information_schema')
  metrics:
    - schemaname:
        usage: "LABEL"
        description: "Name of the schema"
    - tablename:
        usage: "LABEL"
        description: "Name of the table"
    - total_bytes:
        usage: "GAUGE"
        description: "Total size of the table including indexes in bytes"
    - table_bytes:
        usage: "GAUGE"
        description: "Size of the table in bytes"
    - index_bytes:
        usage: "GAUGE"
        description: "Size of indexes in bytes"

# Index usage metrics
pg_index_usage:
  query: |
    SELECT
      schemaname,
      tablename,
      indexname,
      idx_scan,
      idx_tup_read,
      idx_tup_fetch
    FROM pg_stat_user_indexes
  metrics:
    - schemaname:
        usage: "LABEL"
    - tablename:
        usage: "LABEL"
    - indexname:
        usage: "LABEL"
    - idx_scan:
        usage: "COUNTER"
        description: "Number of index scans initiated"
    - idx_tup_read:
        usage: "COUNTER"
        description: "Number of index entries returned"
    - idx_tup_fetch:
        usage: "COUNTER"
        description: "Number of live rows fetched"

# Table statistics
pg_stat_user_tables:
  query: |
    SELECT
      schemaname,
      relname,
      seq_scan,
      seq_tup_read,
      idx_scan,
      idx_tup_fetch,
      n_tup_ins,
      n_tup_upd,
      n_tup_del,
      n_live_tup,
      n_dead_tup,
      vacuum_count,
      autovacuum_count,
      analyze_count,
      autoanalyze_count
    FROM pg_stat_user_tables
  metrics:
    - schemaname:
        usage: "LABEL"
    - relname:
        usage: "LABEL"
    - seq_scan:
        usage: "COUNTER"
        description: "Sequential scans"
    - seq_tup_read:
        usage: "COUNTER"
        description: "Tuples read by sequential scans"
    - idx_scan:
        usage: "COUNTER"
        description: "Index scans"
    - idx_tup_fetch:
        usage: "COUNTER"
        description: "Tuples fetched by index scans"
    - n_tup_ins:
        usage: "COUNTER"
        description: "Tuples inserted"
    - n_tup_upd:
        usage: "COUNTER"
        description: "Tuples updated"
    - n_tup_del:
        usage: "COUNTER"
        description: "Tuples deleted"
    - n_live_tup:
        usage: "GAUGE"
        description: "Live tuples"
    - n_dead_tup:
        usage: "GAUGE"
        description: "Dead tuples"
    - vacuum_count:
        usage: "COUNTER"
        description: "Manual vacuum count"
    - autovacuum_count:
        usage: "COUNTER"
        description: "Autovacuum count"
    - analyze_count:
        usage: "COUNTER"
        description: "Manual analyze count"
    - autoanalyze_count:
        usage: "COUNTER"
        description: "Autoanalyze count"

# Connection statistics
pg_stat_database:
  query: |
    SELECT
      datname,
      numbackends,
      xact_commit,
      xact_rollback,
      blks_read,
      blks_hit,
      tup_returned,
      tup_fetched,
      tup_inserted,
      tup_updated,
      tup_deleted,
      conflicts,
      temp_files,
      temp_bytes,
      deadlocks
    FROM pg_stat_database
    WHERE datname NOT IN ('template0', 'template1')
  metrics:
    - datname:
        usage: "LABEL"
    - numbackends:
        usage: "GAUGE"
        description: "Number of backends connected to this database"
    - xact_commit:
        usage: "COUNTER"
        description: "Transactions committed"
    - xact_rollback:
        usage: "COUNTER"
        description: "Transactions rolled back"
    - blks_read:
        usage: "COUNTER"
        description: "Disk blocks read"
    - blks_hit:
        usage: "COUNTER"
        description: "Buffer hits"
    - tup_returned:
        usage: "COUNTER"
        description: "Tuples returned"
    - tup_fetched:
        usage: "COUNTER"
        description: "Tuples fetched"
    - tup_inserted:
        usage: "COUNTER"
        description: "Tuples inserted"
    - tup_updated:
        usage: "COUNTER"
        description: "Tuples updated"
    - tup_deleted:
        usage: "COUNTER"
        description: "Tuples deleted"
    - conflicts:
        usage: "COUNTER"
        description: "Query conflicts"
    - temp_files:
        usage: "COUNTER"
        description: "Temporary files created"
    - temp_bytes:
        usage: "COUNTER"
        description: "Temporary bytes written"
    - deadlocks:
        usage: "COUNTER"
        description: "Deadlocks detected"

# Replication lag
pg_replication_lag:
  query: |
    SELECT
      application_name,
      client_addr,
      state,
      COALESCE(pg_wal_lsn_diff(pg_current_wal_lsn(), replay_lsn), 0) AS lag_bytes
    FROM pg_stat_replication
  master: true
  metrics:
    - application_name:
        usage: "LABEL"
    - client_addr:
        usage: "LABEL"
    - state:
        usage: "LABEL"
    - lag_bytes:
        usage: "GAUGE"
        description: "Replication lag in bytes"

# Long running queries
pg_long_running_queries:
  query: |
    SELECT
      COUNT(*) FILTER (WHERE state = 'active' AND now() - query_start > interval '5 seconds') AS active_5s,
      COUNT(*) FILTER (WHERE state = 'active' AND now() - query_start > interval '30 seconds') AS active_30s,
      COUNT(*) FILTER (WHERE state = 'active' AND now() - query_start > interval '1 minute') AS active_1m,
      COUNT(*) FILTER (WHERE state = 'active' AND now() - query_start > interval '5 minutes') AS active_5m
    FROM pg_stat_activity
    WHERE pid != pg_backend_pid()
  metrics:
    - active_5s:
        usage: "GAUGE"
        description: "Queries running longer than 5 seconds"
    - active_30s:
        usage: "GAUGE"
        description: "Queries running longer than 30 seconds"
    - active_1m:
        usage: "GAUGE"
        description: "Queries running longer than 1 minute"
    - active_5m:
        usage: "GAUGE"
        description: "Queries running longer than 5 minutes"
