# Promtail Configuration for ORION Platform
# Collects logs from Docker containers and forwards to Loki

server:
  http_listen_port: 9080
  grpc_listen_port: 0
  log_level: info

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push
    batchwait: 1s
    batchsize: 1048576
    timeout: 10s
    backoff_config:
      min_period: 500ms
      max_period: 5m
      max_retries: 10

scrape_configs:
  # Docker container logs
  - job_name: docker
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s
        filters:
          - name: label
            values: ["com.docker.compose.project=orion"]
    relabel_configs:
      - source_labels: ['__meta_docker_container_name']
        regex: '/(.*)'
        target_label: 'container'
      - source_labels: ['__meta_docker_container_log_stream']
        target_label: 'stream'
      - source_labels: ['__meta_docker_container_label_com_docker_compose_service']
        target_label: 'service'
      - source_labels: ['__meta_docker_container_label_com_docker_compose_project']
        target_label: 'project'
    pipeline_stages:
      # Parse JSON logs
      - json:
          expressions:
            timestamp: time
            level: level
            message: msg
            trace_id: trace_id
            span_id: span_id
            service: service
      # Set log level as a label
      - labels:
          level:
          service:
          trace_id:
      # Parse timestamp
      - timestamp:
          source: timestamp
          format: RFC3339Nano
      # Output stage
      - output:
          source: message

  # System logs
  - job_name: system
    static_configs:
      - targets:
          - localhost
        labels:
          job: varlogs
          __path__: /var/log/*log
    pipeline_stages:
      - match:
          selector: '{job="varlogs"}'
          stages:
            - regex:
                expression: '^(?P<timestamp>\S+\s+\S+)\s+(?P<hostname>\S+)\s+(?P<process>\S+)(\[(?P<pid>\d+)\])?: (?P<message>.*)$'
            - labels:
                hostname:
                process:
            - timestamp:
                source: timestamp
                format: 'Jan 02 15:04:05'

  # Application logs from files
  - job_name: orion-apps
    static_configs:
      - targets:
          - localhost
        labels:
          job: orion
          __path__: /var/log/orion/*.log
    pipeline_stages:
      - json:
          expressions:
            timestamp: time
            level: level
            service: service
            message: msg
            trace_id: trace_id
      - labels:
          level:
          service:
          trace_id:
      - timestamp:
          source: timestamp
          format: RFC3339Nano
