{
 "title": "Service Communication",
 "tags": [
  "istio",
  "service-mesh",
  "communication",
  "orion"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": "label_values(istio_requests_total, destination_service_namespace)"
   },
   {
    "name": "source_service",
    "query": "label_values(istio_requests_total{destination_service_namespace=\"$namespace\"}, source_app)"
   },
   {
    "name": "destination_service",
    "query": "label_values(istio_requests_total{destination_service_namespace=\"$namespace\"}, destination_service_name)"
   }
  ]
 },
 "panels": [
  {
   "title": "Service-to-Service Traffic Map",
   "type": "nodeGraph",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(istio_requests_total{destination_service_namespace=\"$namespace\"}[5m])) by (source_app, destination_service_name)"
    }
   ]
  },
  {
   "title": "Inbound Traffic Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "reqps", "label": "Requests/sec" }
   ],
   "targets": [
    {
     "expr": "sum(rate(istio_requests_total{reporter=\"destination\",destination_service_namespace=\"$namespace\",destination_service_name=~\"$destination_service\"}[5m])) by (source_app)",
     "legendFormat": "from {{source_app}}"
    }
   ]
  },
  {
   "title": "Outbound Traffic Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "reqps", "label": "Requests/sec" }
   ],
   "targets": [
    {
     "expr": "sum(rate(istio_requests_total{reporter=\"source\",source_app=~\"$source_service\",destination_service_namespace=\"$namespace\"}[5m])) by (destination_service_name)",
     "legendFormat": "to {{destination_service_name}}"
    }
   ]
  },
  {
   "title": "Request Success Rate by Source",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "percent", "label": "Success Rate" }
   ],
   "targets": [
    {
     "expr": "sum(rate(istio_requests_total{reporter=\"destination\",destination_service_namespace=\"$namespace\",response_code!~\"5..\"}[5m])) by (source_app) / sum(rate(istio_requests_total{reporter=\"destination\",destination_service_namespace=\"$namespace\"}[5m])) by (source_app) * 100",
     "legendFormat": "{{source_app}}"
    }
   ]
  },
  {
   "title": "Request Duration by Service Pair",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "targets": [
    {
     "expr": "sum(rate(istio_request_duration_milliseconds_bucket{reporter=\"destination\",destination_service_namespace=\"$namespace\"}[5m])) by (source_app, destination_service_name, le)"
    }
   ]
  },
  {
   "title": "Failed Requests by Service Pair",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "sum(rate(istio_requests_total{reporter=\"destination\",destination_service_namespace=\"$namespace\",response_code=~\"5..\"}[5m])) by (source_app, destination_service_name, response_code) > 0"
    }
   ]
  },
  {
   "title": "Retry Rate by Service",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
   "yaxes": [
    { "format": "reqps", "label": "Retries/sec" }
   ],
   "targets": [
    {
     "expr": "sum(rate(envoy_cluster_upstream_rq_retry{cluster_name=~\"outbound.*$namespace.*\"}[5m])) by (cluster_name)",
     "legendFormat": "{{cluster_name}}"
    }
   ]
  },
  {
   "title": "Connection Pool Status",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "short", "label": "Connections" }
   ],
   "targets": [
    {
     "expr": "envoy_cluster_upstream_cx_active{cluster_name=~\"outbound.*$namespace.*\"}",
     "legendFormat": "{{cluster_name}} - Active"
    },
    {
     "expr": "envoy_cluster_upstream_cx_overflow{cluster_name=~\"outbound.*$namespace.*\"}",
     "legendFormat": "{{cluster_name}} - Overflow"
    }
   ]
  },
  {
   "title": "Request/Response Size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
   "yaxes": [
    { "format": "bytes", "label": "Avg Size" }
   ],
   "targets": [
    {
     "expr": "sum(rate(istio_request_bytes_sum{reporter=\"destination\",destination_service_namespace=\"$namespace\"}[5m])) by (destination_service_name) / sum(rate(istio_request_bytes_count{reporter=\"destination\",destination_service_namespace=\"$namespace\"}[5m])) by (destination_service_name)",
     "legendFormat": "{{destination_service_name}} - Request"
    },
    {
     "expr": "sum(rate(istio_response_bytes_sum{reporter=\"destination\",destination_service_namespace=\"$namespace\"}[5m])) by (destination_service_name) / sum(rate(istio_response_bytes_count{reporter=\"destination\",destination_service_namespace=\"$namespace\"}[5m])) by (destination_service_name)",
     "legendFormat": "{{destination_service_name}} - Response"
    }
   ]
  }
 ]
}