apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-ui
  namespace: orion
  labels:
    app: admin-ui
    component: frontend
    version: v1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: admin-ui
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: admin-ui
        component: frontend
        version: v1
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "3004"
        prometheus.io/path: "/metrics"
    spec:
      serviceAccountName: admin-ui
      securityContext:
        runAsNonRoot: true
        runAsUser: 1001
        fsGroup: 1001
        seccompProfile:
          type: RuntimeDefault
      containers:
      - name: admin-ui
        image: orion/admin-ui:latest
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 3004
          protocol: TCP
        env:
        - name: NODE_ENV
          value: "production"
        - name: PORT
          value: "3004"
        - name: GATEWAY_URL
          value: "http://gateway:3000"
        - name: AUTH_SERVICE_URL
          value: "http://auth:3001"
        - name: USER_SERVICE_URL
          value: "http://user:3002"
        - name: NOTIFICATION_SERVICE_URL
          value: "http://notifications:3003"
        envFrom:
        - configMapRef:
            name: admin-ui-config
        - secretRef:
            name: admin-ui-secrets
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi
        livenessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          successThreshold: 1
          failureThreshold: 3
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 1001
          capabilities:
            drop:
            - ALL
        volumeMounts:
        - name: tmp
          mountPath: /tmp
        - name: cache
          mountPath: /app/.cache
      volumes:
      - name: tmp
        emptyDir: {}
      - name: cache
        emptyDir: {}
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - admin-ui
              topologyKey: kubernetes.io/hostname
