apiVersion: v1
kind: Service
metadata:
  name: admin-ui
  namespace: orion
  labels:
    app: admin-ui
    component: frontend
spec:
  type: ClusterIP
  ports:
  - port: 3004
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app: admin-ui
