apiVersion: v1
kind: Service
metadata:
  name: gateway
  namespace: orion
  labels:
    app: gateway
    tier: api
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: gateway
  sessionAffinity: None
