# Production environment values
global:
  environment: production
  domain: orion.com
  imagePullPolicy: IfNotPresent

gateway:
  replicaCount: 3
  autoscaling:
    minReplicas: 3
    maxReplicas: 20
  resources:
    requests:
      cpu: 200m
      memory: 256Mi
    limits:
      cpu: 1000m
      memory: 1Gi

auth:
  replicaCount: 5
  autoscaling:
    minReplicas: 5
    maxReplicas: 20
  resources:
    requests:
      cpu: 200m
      memory: 256Mi
    limits:
      cpu: 1000m
      memory: 1Gi

user:
  replicaCount: 3
  autoscaling:
    minReplicas: 3
    maxReplicas: 20
  persistence:
    size: 50Gi
  resources:
    requests:
      cpu: 200m
      memory: 256Mi
    limits:
      cpu: 1000m
      memory: 1Gi

notifications:
  replicaCount: 3
  autoscaling:
    minReplicas: 3
    maxReplicas: 20
  resources:
    requests:
      cpu: 200m
      memory: 256Mi
    limits:
      cpu: 1000m
      memory: 1Gi

adminUi:
  replicaCount: 3
  autoscaling:
    minReplicas: 3
    maxReplicas: 10
  resources:
    requests:
      cpu: 200m
      memory: 256Mi
    limits:
      cpu: 1000m
      memory: 1Gi

postgresql:
  persistence:
    size: 100Gi
    storageClass: fast-ssd
  resources:
    requests:
      cpu: 500m
      memory: 512Mi
    limits:
      cpu: 2000m
      memory: 2Gi
  replication:
    enabled: true
    replicas: 2

redis:
  persistence:
    size: 10Gi
    storageClass: fast-ssd
  resources:
    requests:
      cpu: 200m
      memory: 256Mi
    limits:
      cpu: 1000m
      memory: 1Gi
  sentinel:
    enabled: true

rabbitmq:
  persistence:
    size: 20Gi
    storageClass: fast-ssd
  resources:
    requests:
      cpu: 500m
      memory: 512Mi
    limits:
      cpu: 2000m
      memory: 2Gi
  clustering:
    enabled: true
    replicas: 3

ingress:
  enabled: true
  tls:
    enabled: true
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/rate-limit: "100"

monitoring:
  enabled: true
  prometheus:
    enabled: true
    retention: 30d
  grafana:
    enabled: true
    persistence:
      enabled: true
      size: 10Gi

security:
  networkPolicies:
    enabled: true
  podSecurityPolicy:
    enabled: true
  podSecurityStandards:
    enforce: restricted
