# Development environment values
global:
  environment: development
  domain: dev.orion.local
  imagePullPolicy: Always

gateway:
  replicaCount: 1
  autoscaling:
    enabled: false
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 256Mi

auth:
  replicaCount: 1
  autoscaling:
    enabled: false
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 256Mi

user:
  replicaCount: 1
  autoscaling:
    enabled: false
  persistence:
    size: 1Gi
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 256Mi

notifications:
  replicaCount: 1
  autoscaling:
    enabled: false
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 256Mi

adminUi:
  replicaCount: 1
  autoscaling:
    enabled: false
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 256Mi

postgresql:
  persistence:
    size: 5Gi
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi

redis:
  persistence:
    size: 1Gi
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 256Mi

rabbitmq:
  persistence:
    size: 2Gi
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi

ingress:
  enabled: false
  tls:
    enabled: false

monitoring:
  enabled: false

security:
  networkPolicies:
    enabled: false
  podSecurityPolicy:
    enabled: false
