# Blue-Green Deployment Configuration for Auth Service
# This manifest includes both blue and green deployments with a service that can switch between them

---
# Blue Deployment (Current/Stable Version)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service-blue
  namespace: orion
  labels:
    app: auth-service
    version: blue
    deployment-strategy: blue-green
    app.kubernetes.io/name: auth-service
    app.kubernetes.io/part-of: orion-platform
    app.kubernetes.io/component: backend
  annotations:
    deployment.kubernetes.io/revision: "blue"
    deployment.orion.io/strategy: "blue-green"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: auth-service
      version: blue
  template:
    metadata:
      labels:
        app: auth-service
        version: blue
        slot: blue
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "3001"
        prometheus.io/path: "/metrics"
        deployment.orion.io/slot: "blue"
    spec:
      serviceAccountName: auth-service
      securityContext:
        runAsNonRoot: true
        runAsUser: 1001
        fsGroup: 1001
      containers:
      - name: auth-service
        image: ghcr.io/orion/auth:latest
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 3001
          protocol: TCP
        env:
        - name: NODE_ENV
          value: "production"
        - name: PORT
          value: "3001"
        - name: DEPLOYMENT_SLOT
          value: "blue"
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: auth-secrets
              key: database-url
        - name: REDIS_URL
          valueFrom:
            secretKeyRef:
              name: auth-secrets
              key: redis-url
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: auth-secrets
              key: jwt-secret
        - name: JWT_ACCESS_EXPIRY
          valueFrom:
            configMapKeyRef:
              name: auth-config
              key: jwt.access.expiry
        - name: JWT_REFRESH_EXPIRY
          valueFrom:
            configMapKeyRef:
              name: auth-config
              key: jwt.refresh.expiry
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi
        livenessProbe:
          httpGet:
            path: /api/auth/health/liveness
            port: http
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /api/auth/health/readiness
            port: http
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          successThreshold: 1
          failureThreshold: 3
        startupProbe:
          httpGet:
            path: /api/auth/health
            port: http
          initialDelaySeconds: 0
          periodSeconds: 10
          timeoutSeconds: 3
          successThreshold: 1
          failureThreshold: 30
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop:
            - ALL
        volumeMounts:
        - name: tmp
          mountPath: /tmp
        - name: cache
          mountPath: /app/.cache
      volumes:
      - name: tmp
        emptyDir: {}
      - name: cache
        emptyDir: {}
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - auth-service
              topologyKey: kubernetes.io/hostname

---
# Green Deployment (New Version)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service-green
  namespace: orion
  labels:
    app: auth-service
    version: green
    deployment-strategy: blue-green
    app.kubernetes.io/name: auth-service
    app.kubernetes.io/part-of: orion-platform
    app.kubernetes.io/component: backend
  annotations:
    deployment.kubernetes.io/revision: "green"
    deployment.orion.io/strategy: "blue-green"
spec:
  replicas: 0  # Initially scaled to 0, scaled up during deployment
  selector:
    matchLabels:
      app: auth-service
      version: green
  template:
    metadata:
      labels:
        app: auth-service
        version: green
        slot: green
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "3001"
        prometheus.io/path: "/metrics"
        deployment.orion.io/slot: "green"
    spec:
      serviceAccountName: auth-service
      securityContext:
        runAsNonRoot: true
        runAsUser: 1001
        fsGroup: 1001
      containers:
      - name: auth-service
        image: ghcr.io/orion/auth:latest
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 3001
          protocol: TCP
        env:
        - name: NODE_ENV
          value: "production"
        - name: PORT
          value: "3001"
        - name: DEPLOYMENT_SLOT
          value: "green"
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: auth-secrets
              key: database-url
        - name: REDIS_URL
          valueFrom:
            secretKeyRef:
              name: auth-secrets
              key: redis-url
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: auth-secrets
              key: jwt-secret
        - name: JWT_ACCESS_EXPIRY
          valueFrom:
            configMapKeyRef:
              name: auth-config
              key: jwt.access.expiry
        - name: JWT_REFRESH_EXPIRY
          valueFrom:
            configMapKeyRef:
              name: auth-config
              key: jwt.refresh.expiry
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi
        livenessProbe:
          httpGet:
            path: /api/auth/health/liveness
            port: http
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /api/auth/health/readiness
            port: http
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          successThreshold: 1
          failureThreshold: 3
        startupProbe:
          httpGet:
            path: /api/auth/health
            port: http
          initialDelaySeconds: 0
          periodSeconds: 10
          timeoutSeconds: 3
          successThreshold: 1
          failureThreshold: 30
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop:
            - ALL
        volumeMounts:
        - name: tmp
          mountPath: /tmp
        - name: cache
          mountPath: /app/.cache
      volumes:
      - name: tmp
        emptyDir: {}
      - name: cache
        emptyDir: {}
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - auth-service
              topologyKey: kubernetes.io/hostname

---
# Service that routes traffic to active slot (blue or green)
apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: orion
  labels:
    app: auth-service
    app.kubernetes.io/name: auth-service
    app.kubernetes.io/part-of: orion-platform
  annotations:
    deployment.orion.io/active-slot: "blue"  # Change to 'green' to switch traffic
    deployment.orion.io/strategy: "blue-green"
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app: auth-service
    slot: blue  # This selector switches between 'blue' and 'green'

---
# Blue-specific service for testing
apiVersion: v1
kind: Service
metadata:
  name: auth-service-blue
  namespace: orion
  labels:
    app: auth-service
    version: blue
    app.kubernetes.io/name: auth-service
    app.kubernetes.io/part-of: orion-platform
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app: auth-service
    slot: blue

---
# Green-specific service for testing
apiVersion: v1
kind: Service
metadata:
  name: auth-service-green
  namespace: orion
  labels:
    app: auth-service
    version: green
    app.kubernetes.io/name: auth-service
    app.kubernetes.io/part-of: orion-platform
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app: auth-service
    slot: green

---
# ServiceAccount (shared between blue and green)
apiVersion: v1
kind: ServiceAccount
metadata:
  name: auth-service
  namespace: orion
  labels:
    app: auth-service
    app.kubernetes.io/name: auth-service
    app.kubernetes.io/part-of: orion-platform
