apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
spec:
  replicas: 5
  template:
    spec:
      containers:
      - name: auth-service
        resources:
          requests:
            cpu: 250m
            memory: 256Mi
          limits:
            cpu: 1000m
            memory: 1Gi
        env:
        - name: NODE_ENV
          value: "production"
        - name: LOG_LEVEL
          value: "info"
        - name: REDIS_CLUSTER_MODE
          value: "true"
        - name: DATABASE_POOL_SIZE
          value: "20"