apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: orion

resources:
- namespace.yaml
- auth-configmap.yaml
- auth-deployment.yaml
- auth-service.yaml
- auth-hpa.yaml
- auth-networkpolicy.yaml
# Monitoring and Observability
- auth-servicemonitor.yaml
# High Availability
- auth-pdb.yaml
# TLS Certificate Management
- issuer.yaml
- certificate.yaml
# External Access
- auth-ingress.yaml

commonLabels:
  app.kubernetes.io/managed-by: kustomize
  app.kubernetes.io/part-of: orion-platform

images:
- name: ghcr.io/orion/auth
  newTag: latest