apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: auth-service-secrets
  namespace: default
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: auth-service-secrets
    creationPolicy: Owner
    template:
      type: Opaque
      engineVersion: v2
  data:
    - secretKey: JWT_SECRET
      remoteRef:
        key: auth-service/jwt
        property: secret
    - secretKey: DATABASE_PASSWORD
      remoteRef:
        key: auth-service/database
        property: password
    - secretKey: REDIS_PASSWORD
      remoteRef:
        key: auth-service/redis
        property: password
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: gateway-service-secrets
  namespace: default
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: gateway-service-secrets
    creationPolicy: Owner
  data:
    - secretKey: API_KEY
      remoteRef:
        key: gateway-service/api
        property: key
    - secretKey: ENCRYPTION_KEY
      remoteRef:
        key: gateway-service/encryption
        property: key
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: notification-service-secrets
  namespace: default
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: notification-service-secrets
    creationPolicy: Owner
  data:
    - secretKey: SMTP_PASSWORD
      remoteRef:
        key: notification-service/smtp
        property: password
    - secretKey: SENDGRID_API_KEY
      remoteRef:
        key: notification-service/sendgrid
        property: apiKey
    - secretKey: TWILIO_AUTH_TOKEN
      remoteRef:
        key: notification-service/twilio
        property: authToken
