apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: vault-backend
  namespace: default
spec:
  provider:
    vault:
      server: "http://vault.vault.svc.cluster.local:8200"
      path: "secret"
      version: "v2"
      auth:
        # Kubernetes authentication
        kubernetes:
          mountPath: "kubernetes"
          role: "orion-services"
          serviceAccountRef:
            name: orion-service-account
---
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: vault-backend-cluster
spec:
  provider:
    vault:
      server: "http://vault.vault.svc.cluster.local:8200"
      path: "secret"
      version: "v2"
      namespace: "admin"
      auth:
        kubernetes:
          mountPath: "kubernetes"
          role: "orion-services"
          serviceAccountRef:
            name: orion-service-account
            namespace: default
