name: Deploy to Staging

on:
  push:
    branches: [staging]
  workflow_dispatch:

env:
  ENVIRONMENT: staging
  NAMESPACE: orion-staging
  REGISTRY: ghcr.io

jobs:
  deploy:
    name: Deploy to Staging
    runs-on: ubuntu-latest
    environment:
      name: staging
      url: https://staging.orion.example.com

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'v1.28.0'

      - name: Configure kubectl
        run: |
          echo "\${{ secrets.KUBE_CONFIG_STAGING }}" | base64 -d > kubeconfig
          export KUBECONFIG=./kubeconfig
          kubectl cluster-info

      - name: Run deployment script
        run: bash scripts/deploy-staging.sh
        env:
          KUBE_CONFIG: ./kubeconfig

      - name: Verify deployment
        run: |
          export KUBECONFIG=./kubeconfig
          kubectl rollout status deployment -n \${{ env.NAMESPACE }} --timeout=10m

      - name: Run smoke tests
        run: bash scripts/smoke-tests.sh staging

      - name: Send notification
        if: always()
        uses: 8398a7/action-slack@v3
        with:
          status: \${{ job.status }}
          webhook_url: \${{ secrets.SLACK_WEBHOOK_URL }}
