apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: orion-staging

bases:
- ../../base

namePrefix: staging-
nameSuffix: ""

commonLabels:
  environment: staging
  app.kubernetes.io/instance: staging

replicas:
- name: auth-service
  count: 2

patchesStrategicMerge:
- auth-deployment-patch.yaml

configMapGenerator:
- name: auth-config
  behavior: merge
  literals:
  - NODE_ENV=staging
  - LOG_LEVEL=debug
  - CORS_ORIGIN=https://staging-api.orion.com

secretGenerator:
- name: auth-secrets
  env: secrets.env
  type: Opaque

images:
- name: ghcr.io/orion/auth
  newTag: develop